version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
