# Start from the official Golang base image
FROM golang:latest as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY src/backend/go.mod src/backend/go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY src/backend/ ./

RUN go build -o main

# # Create cache directory and an empty cache.json file
# RUN mkdir -p cache && touch cache/cache.json

CMD [ "./main" ]
