# Start with the Node.js base image
FROM node:16-alpine as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY src/frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy frontend source files
COPY src/frontend/ .

# Build the React application
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
